# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

**Penjelasan Dataset:** Dataset yang digunakan dalam proyek ini adalah dataset klasifikasi tingkat kemiskinan di Indonesia yang diperoleh dari Kaggle. Dataset ini berisi berbagai atribut sosial ekonomi seperti tingkat pendidikan, pekerjaan, dan kondisi rumah tangga yang digunakan untuk mengklasifikasikan tingkat kemiskinan masyarakat.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
df = pd.read_csv('/content/drive/MyDrive/SEMESTER 6 (STUPEND)/Eksperimen_SML_Angga Prasetio/Klasifikasi Tingkat Kemiskinan di Indonesia.csv',
                 sep=';', decimal=',')

df.head()

,Provinsi,Kab/Kota,Persentase Penduduk Miskin (P0) Menurut Kabupaten/Kota (Persen),Rata-rata Lama Sekolah Penduduk 15+ (Tahun),Pengeluaran per Kapita Disesuaikan (Ribu Rupiah/Orang/Tahun),Indeks Pembangunan Manusia,Umur Harapan Hidup (Tahun),Persentase rumah tangga yang memiliki akses terhadap sanitasi layak,Persentase rumah tangga yang memiliki akses terhadap air minum layak,Tingkat Pengangguran Terbuka,Tingkat Partisipasi Angkatan Kerja,PDRB atas Dasar Harga Konstan menurut Pengeluaran (Rupiah),Klasifikasi Kemiskinan
0,ACEH,Simeulue,"18,98","9,48",7148.0,66.41,65.28,71.56,87.45,5.71,71.15,1648096.0,0.0
1,ACEH,Aceh Singkil,"20,36","8,68",8776.0,69.22,67.43,69.56,78.58,8.36,62.85,1780419.0,1.0
2,ACEH,Aceh Selatan,"13,18","8,88",8180.0,67.44,64.40,62.55,79.65,6.46,60.85,4345784.0,0.0
3,ACEH,Aceh Tenggara,"13,41","9,67",8030.0,69.44,68.22,62.71,86.71,6.43,69.62,3487157.0,0.0
4,ACEH,Aceh Timur,"14,45","8,21",8577.0,67.83,68.74,66.75,83.16,7.13,59.48,8433526.0,0.0

In [14]:
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 13 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Provinsi                                                              514 non-null    object
 1   Kab/Kota                                                              514 non-null    object
 2   Persentase Penduduk Miskin (P0) Menurut Kabupaten/Kota (Persen)       514 non-null    object
 3   Rata-rata Lama Sekolah Penduduk 15+ (Tahun)                           514 non-null    object
 4   Pengeluaran per Kapita Disesuaikan (Ribu Rupiah/Orang/Tahun)          514 non-null    float64
 5   Indeks Pembangunan Manusia                                            514 non-null    float64
 6   Umur Harapan Hidup (Tahun)                                            514 non-null    float64
 7   Persentase rumah tangga yang memiliki akses terhadap sanitasi layak   514 non-null    float64
 8   Persentase rumah tangga yang memiliki akses terhadap air minum layak  514 non-null    float64
 9   Tingkat Pengangguran Terbuka                                          514 non-null    float64
 10  Tingkat Partisipasi Angkatan Kerja                                    514 non-null    float64
 11  PDRB atas Dasar Harga Konstan menurut Pengeluaran (Rupiah)            514 non-null    float64
 12  Klasifikasi Kemiskinan                                                514 non-null    float64
dtypes: float64(9), object(4)
memory usage: 101.6+ KB

Index(['Provinsi', 'Kab/Kota',
       'Persentase Penduduk Miskin (P0) Menurut Kabupaten/Kota (Persen)',
       'Rata-rata Lama Sekolah Penduduk 15+ (Tahun)',
       'Pengeluaran per Kapita Disesuaikan (Ribu Rupiah/Orang/Tahun)',
       'Indeks Pembangunan Manusia', 'Umur Harapan Hidup (Tahun)',
       'Persentase rumah tangga yang memiliki akses terhadap sanitasi layak',
       'Persentase rumah tangga yang memiliki akses terhadap air minum layak',
       'Tingkat Pengangguran Terbuka', 'Tingkat Partisipasi Angkatan Kerja',
       'PDRB atas Dasar Harga Konstan menurut Pengeluaran (Rupiah)',
       'Klasifikasi Kemiskinan'],
      dtype='object')

In [15]:
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.lower()

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 13 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   provinsi                                                              514 non-null    object
 1   kab/kota                                                              514 non-null    object
 2   persentase_penduduk_miskin_(p0)_menurut_kabupaten/kota_(persen)       514 non-null    object
 3   rata-rata_lama_sekolah_penduduk_15+_(tahun)                           514 non-null    object
 4   pengeluaran_per_kapita_disesuaikan_(ribu_rupiah/orang/tahun)          514 non-null    float64
 5   indeks_pembangunan_manusia                                            514 non-null    float64
 6   umur_harapan_hidup_(tahun)                                            514 non-null    float64
 7   persentase_rumah_tangga_yang_memiliki_akses_terhadap_sanitasi_layak   514 non-null    float64
 8   persentase_rumah_tangga_yang_memiliki_akses_terhadap_air_minum_layak  514 non-null    float64
 9   tingkat_pengangguran_terbuka                                          514 non-null    float64
 10  tingkat_partisipasi_angkatan_kerja                                    514 non-null    float64
 11  pdrb_atas_dasar_harga_konstan_menurut_pengeluaran_(rupiah)            514 non-null    float64
 12  klasifikasi_kemiskinan                                                514 non-null    float64
dtypes: float64(9), object(4)
memory usage: 101.6+ KB

In [17]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

In [18]:
df.describe()
df.isnull().sum()

provinsi                                                                485
kab/kota                                                                485
persentase_penduduk_miskin_(p0)_menurut_kabupaten/kota_(persen)         485
rata-rata_lama_sekolah_penduduk_15+_(tahun)                             485
pengeluaran_per_kapita_disesuaikan_(ribu_rupiah/orang/tahun)            485
indeks_pembangunan_manusia                                              485
umur_harapan_hidup_(tahun)                                              485
persentase_rumah_tangga_yang_memiliki_akses_terhadap_sanitasi_layak     485
persentase_rumah_tangga_yang_memiliki_akses_terhadap_air_minum_layak    485
tingkat_pengangguran_terbuka                                            485
tingkat_partisipasi_angkatan_kerja                                      485
pdrb_atas_dasar_harga_konstan_menurut_pengeluaran_(rupiah)              485
klasifikasi_kemiskinan                                                  485
dtype: int64

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

In [41]:
# pisahkan fitur & target (FIX)
X = df.drop(['provinsi', 'kab/kota', 'klasifikasi_kemiskinan'], axis=1)
y = df['klasifikasi_kemiskinan']

# fix angka koma
X = X.apply(lambda x: x.str.replace(',', '.') if x.dtype == "object" else x)

# ubah ke numerik
X = X.apply(pd.to_numeric, errors='coerce')

# hapus null hasil konversi
X = X.dropna()
y = y.loc[X.index]

# scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [42]:
X.dtypes

persentase_penduduk_miskin_(p0)_menurut_kabupaten/kota_(persen)         float64
rata-rata_lama_sekolah_penduduk_15+_(tahun)                             float64
pengeluaran_per_kapita_disesuaikan_(ribu_rupiah/orang/tahun)            float64
indeks_pembangunan_manusia                                              float64
umur_harapan_hidup_(tahun)                                              float64
persentase_rumah_tangga_yang_memiliki_akses_terhadap_sanitasi_layak     float64
persentase_rumah_tangga_yang_memiliki_akses_terhadap_air_minum_layak    float64
tingkat_pengangguran_terbuka                                            float64
tingkat_partisipasi_angkatan_kerja                                      float64
pdrb_atas_dasar_harga_konstan_menurut_pengeluaran_(rupiah)              float64
dtype: object

In [44]:
df.to_csv('/content/drive/MyDrive/SEMESTER 6 (STUPEND)/Eksperimen_SML_Angga Prasetio/data_clean.csv', index=False)